#baseurl = "https://example.org"
baseurl = "http://jkroz.github.io"
title = "PLPerformances"
theme = "hugo-universal-theme"
#themesDir = "../.."
languageCode = "fr-fr"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "fr"
# Enable comments by entering your Disqus shortname
#disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

#[[menu.main]]
#    identifier="home"
#    name = "Home"
#    url  = "/"
#    weight = 1

#[[menu.main]]
#    identifier="blog"
#    name = "Blog"
#    url  = "/blog/"
#    weight = 2

#[[menu.main]]
#    identifier = "faq"
#    name = "FAQ"
#    url  = "/faq/"
#    weight = 3

#[[menu.main]]
#    identifier = "contact"
#    name = "Contact"
#    url  = "/contact/"
#    weight = 4

# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "GitHub"
#    url = "https://github.com/devcows/hugo-universal-theme"
#    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://fr-fr.facebook.com/pages/category/Motorcycle-Repair-Shop/PL-Performances-358337364299763/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

#[[menu.topbar]]
#    weight = 3
#    name = "Twitter"
#    url = "http://twitter.com"
#    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:pl@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by devcows using hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = ""

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "red"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    #formspree_action = "https://formspree.io/sample/of/endpoint"
    #contact_form_ajax = false

    about_us = """
    <p>Atelier de mécanique moto proposant tout types de service relatif aux 2 roues.</p>
    <p>Un service complet pour votre 2 roues, que ce soit unes révision, une réparation ou une préparation moteur votre 2 roues sera entre de bonnes mains.</p>
    <p>Une équipe de professionnel reconnu sera répondre à vos attentes.</p><br>
    """

    copyright = "Copyright (c) 2020 - 2021, PL Performances, all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/pl-logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><strong>PL Performances.</strong>
        <br><br>9 Bis Rue des Chevrettes,
        <br>78250, Hardricourt
        <br>
        <br>
        <strong>France</strong>
        <p><b>Téléphone :</b> 01 30 22 00 71</p>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs"><b>Téléphone :</b> 01 30 22 00 71</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
